TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += devHPE3631A.db
DB_INSTALLS += $(TOP)/HPE3631ASup/devHPE3631A.proto

#=======================================
include $(TOP)/configure/RULES
