TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
DB += dbExample1.db
DB += dbExample2.db
DB += dbSubExample.db

# User Db
DB += dbTr1.vdb
DB += dbTr2.vdb
DB += dbStr.vdb
DB += dbTStr.vdb
DB += dbTr1Final.vdb
DB += dbSEQ.vdb
DB += dbSubLisaju.vdb
DB += dbPing.vdb
DB += dbCHFailover.vdb
DB += gauss.db
DB += sincalc.db

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

