TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += devkeithley6514.db
DB_INSTALLS += $(TOP)/keithley6514Sup/devkeithley6514.proto

#=======================================
include $(TOP)/configure/RULES
